# Generated by Django 4.2 on 2024-06-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant2", "0003_remove_order_restaurant2_restaur_837b66_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["status"], name="restaurant2_status_bd17b8_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["created_at"], name="restaurant2_created_6e6cff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["updated_at"], name="restaurant2_updated_5d1af9_idx"
            ),
        ),
    ]
